### PR TITLE
Update BlogHomeScreen to refresh data on pull-down

### PR DESCRIPTION
**Pull request by zackha**
### Changes
- Added `RefreshControl` to `BlogHomeScreen` to enable pull-to-refresh functionality.
- Triggered `postStore.getPosts` to fetch new data from the API after clearing the posts.

### Why?
This improves the user experience by allowing users to fetch the latest data by pulling down on the screen.

### CODE REVIEW

**Comment by burhanyilmaz** [comment]
Hi @zackha, thank you for your contribution! That's a good point.
When you trigger `postStore.getPosts`, the API fetches posts related to the current page:

```javascript
const posts = await api.getPost(self.page);
```
If you are on the first page (page 1), there is no issue. However, if you are on a page other than the first (e.g., page 2), the API only fetches posts related to the current page (page 2) and does not retrieve posts from the first page. You need to reset page value.  After that another issue is that after fetching the posts on the first page, the data outside of the first page needs to be removed. What do you think about it?

can you implement it like that?

**Comment by zackha** [comment]
Hey @burhanyilmaz,

Thanks so much for catching that and sharing your feedback! I’ve updated the code to fix the issues you mentioned:
- The `page` now resets to `1` on refresh.
- Existing posts are cleared before pulling in fresh data.
- Only the first page’s posts are kept after refreshing to keep things clean.

Let me know if there’s anything else I should tweak. Appreciate your help on this!

**Comment by burhanyilmaz** [comment]
@zackha  After pull to refresh, there are two loading indicators and a white screen.
Can you try this?
I updated code like that. 
- added pullToRefresh 

### BlogHomeScreen
```
import HomeSlider from '@components/HomeSlider';
import Post from '@containers/Post';
import { BlogStackNavigatorParamList } from '@navigators/BlogNavigator';
import { NavigationProp, useNavigation } from '@react-navigation/native';
import postStore, { PostType } from '@store/PostStore';
import savedStore from '@store/SavedStore';
import searchStore from '@store/SearchStore';
import colors from '@theme/colors';
import { text } from '@theme/text';
import { observer } from 'mobx-react-lite';
import { useEffect } from 'react';
import {
  ActivityIndicator,
  FlatList,
  ListRenderItem,
  RefreshControl,
  Text,
  View,
} from 'react-native';

const BlogHomeScreen = () => {
  const { navigate } = useNavigation<NavigationProp<BlogStackNavigatorParamList>>();

  useEffect(
    () => () => {
      postStore.clearAll();
      savedStore.clearAll();
      searchStore.clearAll();
    },
    [],
  );

  const onEndReached = () => {
    if (postStore.pullToRefresh) {
      return;
    }

    postStore.increasePage();
  };

  const onRefresh = () => {
    postStore.setPullToRefresh(true);
    postStore.getPosts();
  };

  const RenderItem: ListRenderItem<PostType> = ({ item: post }) => (
    <View className="px-5">
      <Post post={post} onPressPost={() => navigate('PostDetail', { post })} />
    </View>
  );

  const RenderListHeader = () => (
    <View>
      <HomeSlider
        posts={postStore.sliderPosts}
        onPressPost={post => navigate('PostDetail', { post })}
      />
      <Text className={text({ type: 'subtitle', class: 'text-left opacity-50 mx-4 mb-2' })}>
        All Posts
      </Text>
    </View>
  );

  return (
    <View className="bg-white flex-1">
      {postStore.loading && postStore.listingPosts.length > 0 && (
        <ActivityIndicator
          size="large"
          color={colors.zinc[600]}
          className="absolute z-50 right-0 left-0 bottom-4"
        />
      )}
      <FlatList
        windowSize={6}
        removeClippedSubviews
        initialNumToRender={6}
        maxToRenderPerBatch={6}
        renderItem={RenderItem}
        onEndReached={onEndReached}
        data={postStore.listingPosts}
        ListHeaderComponent={RenderListHeader}
        ListEmptyComponent={<ActivityIndicator size="large" color={colors.zinc[600]} />}
        refreshControl={
          <RefreshControl refreshing={postStore.pullToRefresh} onRefresh={onRefresh} />
        }
      />
    </View>
  );
};

export default observer(BlogHomeScreen);
```

### postStore.ts
```
import { api } from '@services/Api';
import { removeHtmlAndDecimalEntities } from '@utils/helpers';
import { ApiPostType } from '@utils/types/BlogTypes';
import { when } from 'mobx';
import { Instance, flow, t } from 'mobx-state-tree';

export const Post = t
  .model('Post', {
    link: t.string,
    title: t.string,
    id: t.identifier,
    content: t.string,
    mediaUrl: t.string,
    image: t.maybe(t.string),
    category: t.maybe(t.string),
    categories: t.array(t.string),
    headerImage: t.maybe(t.string),
    imageLoaded: t.maybe(t.boolean),
  })
  .actions(self => ({
    fetchMedia: flow(function* () {
      if (!self.mediaUrl) {
        return;
      }

      const media = yield api.getMediaByUrl(self.mediaUrl);
      const mediaSizes = media?.media_details;
      const renderedMedia = media?.guid?.rendered;

      self.image = mediaSizes?.medium?.source_url || renderedMedia;
      self.headerImage = mediaSizes?.large?.source_url || renderedMedia;
      self.imageLoaded = true;
    }),

    fetchCategory: flow(function* () {
      if (!self.id) {
        self.category = 'Category';

        return;
      }

      const category = yield api.getCategories(self.id);
      self.category = removeHtmlAndDecimalEntities(category[0]?.name) || 'Category';
    }),

    async afterCreate() {
      this.fetchMedia();
    },
  }));

const PostStore = t
  .model('PostStore', {
    url: t.string,
    page: t.number,
    posts: t.map(Post),
    loading: t.optional(t.boolean, false),
    pullToRefresh: t.optional(t.boolean, false),
  })
  .views(self => ({
    get listingPosts() {
      return Array.from(self.posts.values()).slice(4, self.posts.size);
    },

    getSelectedPost(id: string) {
      return self.posts.get(id);
    },

    get sliderPosts() {
      return Array.from(self.posts.values()).slice(0, 4);
    },
  }))
  .actions(self => ({
    setUrl: (url: string) => {
      api.createApiInstance(url);
      self.url = url;
    },

    addPost: (post: ApiPostType) => {
      self.posts.set(
        post.id,
        Post.create({
          link: post.link,
          id: post.id.toString(),
          content: post.content.rendered,
          mediaUrl: post?._links?.['wp:featuredmedia']?.[0]?.href || '',
          title: removeHtmlAndDecimalEntities(post?.title?.rendered || ''),
          category: removeHtmlAndDecimalEntities(post?.primary_category?.name || ''),
          categories: (post.categories || post.section)
            ?.slice(0, 2)
            .map(category => category.toString()),
        }),
      );
    },

    setLoading(loading: boolean) {
      self.loading = loading;
    },

    setPullToRefresh(pullToRefresh: boolean) {
      self.pullToRefresh = pullToRefresh;
    },

    async getPosts() {
      if (!self.url) {
        return;
      }
      this.setLoading(true);

      try {
        if (self.pullToRefresh) {
          self.page = 1;
        }
        const posts = await api.getPost(self.page);

        if (self.pullToRefresh) {
          this.clearAll();

          setTimeout(() => {
            this.setPullToRefresh(false);
          }, 1000);
        }

        if (posts?.length > 0) {
          posts.forEach(this.addPost);
        }

        this.setLoading(false);

        return posts;
      } catch {
        this.setLoading(false);

        return [];
      }
    },

    afterCreate() {
      api.createApiInstance(self.url);
    },

    increasePage() {
      self.page = self.page + 1;
      this.getPosts();
    },

    clearAll() {
      self.posts.clear();
    },
  }));

const postStore = PostStore.create({
  page: 1,
  url: '',
});

export default postStore;

export type PostType = Instance<typeof Post>;


```

**Comment by zackha** [comment]
Hey @burhanyilmaz, 

Thanks for the updated code! I’ve applied the changes you suggested and pushed them. 
Let me know if there’s anything else I should tweak.

**Comment by burhanyilmaz** [comment]
@zackha Thank you for that 💯 🚀

**Pull request merged**
